server.port=8888
spring.application.name=pizza-config-server

# Use the 'native' profile to load config files from the local classpath
spring.profiles.active=native

# Location where we will put the other services' properties files
spring.cloud.config.server.native.search-locations=classpath:/config/